# @format

name: CI

on: [push, pull_request, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: sudo apt-get update
      - uses: lix-pm/setup-lix@master
      - uses: HaxeFlixel/setup-flixel@master
        with:
          haxe-version: stable
          flixel-versions: release
          target: html5
      - run: haxelib install flixel-addons
      - run: haxelib git logging https://github.com/core-haxe/logging --skip-dependencies
      - run: haxelib git queues-core https://github.com/core-haxe/queues-core --skip-dependencies
      - run: haxelib git promises https://github.com/core-haxe/promises --skip-dependencies
      - run: haxelib git http https://github.com/core-haxe/http --skip-dependencies
      - run: haxelib install ldtk-haxe-api 1.5.3-rc.1
      - run: haxelib install deepnightLibs
      - run: haxelib git gif https://github.com/snowkit/gif
      - run: haxelib install json2object
      - run: haxelib install ase
      - name: Build
        run: haxelib run lime build html5 -final -Ddev -Drandom_username -Dtest_local
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./export/html5/bin
          force_orphan: true
        if: github.ref == 'refs/heads/master'
